### ISSUE TITLE
Creeaza strucura website

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#1]
### Summary
Meniul trebuie sa fie relevant pentru continutul accesat, atat in RO cat si in EN. Toate sectiunile website-ului trebuie acoperite cu butoane de navigare din fiecare pagina. 
### Intended Outcome
Site-ul trebuie sa fie usor de navigat cu ajutorul meniurilor clare, Accesul la continut sa fie usor din orice pagina. 
#### Structura 
1. **Header**
  * nume sau logo stanga sus
  * meniu principal
  * meniu schimbare limba 
2. **Pagini**
  * Home – contine informatii despre ceea ce facem, misionea si valorile
  * Povestea noastra – cum s-a “nascut” asociatia si proiectul trip and pick
  * Proiecte – upcoming si past events. Eventual facem un calendar de evenimente
  * Media – declaratii de presa si alte informatii de interes public
  * Implica-te – donatii, social media share 
  * Hai in echipa – detalii despre cum poti deveni voluntar, intern etc
  * Politica de confidentialitate a datelor cu caracter personal - terti cu care colaboram (ex. Analytics, social media widgets, politica de cookie, etc
  * Rapoarte de activitate - sumar al evenimentelor/actiunilor pe care le-am desfasurat (momentan putem mentiona ce am facut pe trip and pick
  * Termeni si conditii - cateva aspecte generale ale regulamentului intern si felul in care colaboram cu interni/voluntari
  * Individual event page - for each upcoming event - information about date/time and location. Page update event: activity report & photo gallery. 
3. **Footer**
  * contact: emai; telefon
  * meniu footer
  * meniu transparenta si GDPR
  * logo powered by dlot
#### Meniuri 
1. **principal**
  * Mission statement/Misiunea (homepage)
  * Our story/Povestea
  * Projects/Proiecte
  * News/Media
  * Support us/Implica-te
  * Join our team/Hai in echipa
2. **footer**
  * Projects/Proiecte
  * News/Media
  * Support us/Implica-te
3. **transparenta si GDPR**
  * Privacy policy/Politica de confidentialitate
  * Activity reports/Rapoarte de activitate
  * Terms and conditions/Termeni si conditii

**Comment by archblob** [comment]
What's the reasoning behind the **footer** menu?
It seems to just be a subset of the main menu.
If it's for when the visitor is at the bottom of the page then I propose we always keep the top menu at the top of the
view and scroll the content underneath. It's a way to not duplicate the top menu.

**Comment by Traveler3568** [comment]
Sticky menu? Ok. Then maybe we should put more relevant links at the bottom (like donate)  to highlight what it's more important for us, even if it repeats.

**Comment by Traveler3568** [comment]
Am adaugat la structura paginile de transparenta si GDPR

**Comment by Traveler3568** [comment]
Am adaugat la structura si pagina individuala pentru evenimente

**Comment by archblob** [comment]
Is there anything that needs porting or adjusting in this initial stage?

**Comment by Traveler3568** [comment]
Photo gallery proposal - https://www.nationalgeographic.com/photo-galleries/
