### ISSUE TITLE
Create expansion panels for Join Our Team page

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#17]
### Summary
Create accordion in page

### Intended Outcome
Structure page to highlight job titles for easier in-page navigation

### How will it work?
Accordion with arrow down for 7 job titles, to lead the visitor into finding out attributions and requirements for a specific job title. 

---
Title: Join Asociatia Community powered by DLOT
Descriptions: Call for volunteers Asociatia Community powered by DLOT
---

### Call for volunteers

You're a student looking for opportunities to test and improve your skills, gain working experience, or, you simply like our concept?

Does your personality fit our [values](https://asociatiacommunity.ro/)?   
Would you like to contribute to make the world a better place?  
Do you have any talents/skills that can help us achieve our mission?   
Would you like to develop those skills?  
Are you interested in gaining hand-on experience on a certain position/department?  
Do you like spending time outdoors?  
Do you have the willingness to learn and the courage to test your ideas?

If the answer is Yes, you're in the right place. 

Welcome!

### Many hands make light work <br></br>

We’re looking for volunteers for remote positions or environment clean-up projects.  
As we just started our activity, we can offer you many possibilities. Check-out the list below and [write us](mailto:team@asociatiacommunity.ro) if something piques your interest. 

Maybe you like to write stories, or you’re good at planning and organizing, you have a passion for people, animals and nature, you’re creative, or you like to spend time outdoors and want to join us in our Trip&Pick campaigns. It doesn't matter if you don't check all the requirements for a position. Tell us what you would like to do and how much time you can commit, and we will find a way to highlight your skills.  

**What's in it for you**
* Flexible schedule;
* Work from wherever you want;  
* Based on the level of involvement and results, there is the possibility to be hired in the future;  
* Expenditures such as transport, fuel, stationary, prints and other, are reimbursed;  
* Being at the beginning of our activity, your contribution can be easily quantified to measure the value added to the company’s growth;  
* Participate to brainstorming and your ideas will be taken into account. You can also propose campaigns and strategies, even business direction;  
* You’ll lead the change in society, labor market, employers and brands, towards a sustainable development;  
* Free access to our events;  
* Opportunity to become adhere as a member of the NGO;  
* You have nothing to lose, you can quit at any time you feel it no longer suits you or if we did not meet your expectations.

[comment]: # (accordion - job titles)

## HR Specialist

**Attributions**
* Create, implement, and evaluate human resource department policies and procedures;  
* Recruit and coordinate interviewing;  
* Ensuring new hire paperwork is completed and processed;  
* Informing job applicants of job duties, responsibilities, benefits, schedules, working conditions, promotion opportunities, etc.;  
* Design and implement effective training and development plans.;   
* Perform employee performance evaluations;  
* Keep track of staff schedule  and working hours;  
* Create and deliver activity reports for members and volunteers.

**Requirements**
* Knowledge of labor legislation processes;  
* Understanding of the recruitment process;  
* Verbal and written communication skills;  
* Solid problem-solving and team management abilities;  
* Computer skills using Microsoft Office or other similar software;  
* Personal computer with internet connection;  
* Team player.

### Social media manager

**Attributions**
* Develop, implement and manage our social media strategy;  
* Create and publish relevant, original, engaging content;   
* Manage and oversee social media content;  
* Suggest and implement new features to develop brand awareness, like promotions and competitions;  
* Measure the success of every social media campaign;  
* Stay up to date with latest social media best practices and technologies;  
* Attend educational conferences/work-shops;  
* Analyze and improve social media engagement. 

**Requirements**
* Organizational and time-management abilities;  
* Creative skills;  
* Copywriting skills;  
* Data analysis skills;  
* Computer skills using Microsoft Office or other similar software;  
* Knowledge of social media platforms such as Facebook, Twitter, LinkedIn and Instagram;  
* Personal computer with internet connection;  
* Team player.

### Community & Stakeholder Manager

**Attributions**
* Identify stakeholders;  
* Create, maintain and grow stakeholder database;  
* Establish, maintain and grow community partnerships;  
* Develop and implement a stakeholder and community relations program;  
* Manage our relationship with various different local councils and groups;  
* Maintain and communicate donations, sponsorships and community programs;  
* Manage stakeholder and community issues and provide advice to the project team on communications, community and stakeholder relations activities;  
* Identify and manage any risks associated with the community and stakeholders;  

**Requirements**
* Written and verbal skills (English and Romanian);  
* Ability to build relationships, motivate and inspire diverse groups;  
* Attention to detail and good organizational skills;   
* Understanding of communications and engagement methodologies;   
* Problem-solving skills;  
* Computer skills using Microsoft Office or other similar software;   
* Personal computer with internet connection;  
* Team player.

### Project manager

**Attributions**
* Determine and define project objectives;  
* Plan and designate project resources;  
* Predict project budgets and other resources needed to reach objectives;  
* Manage resources in an effective and efficient manner;  
* Track project costs in order to meet budget;  
* Monitor progress, and keep stakeholders informed the entire way;  
* Develop and manage a detailed project schedule and work plan;  
* Manage contracts with vendors and suppliers by assigning tasks and communicating expected deliverables;  
* Utilize industry best practices, techniques, and standards throughout entire project execution;  
* Measure project performance to identify areas for improvement.

**Requirements**
* Written and verbal skills (English and Romanian);  
* Ability to build relationships, motivate and inspire diverse groups;  
* Attention to detail and good organizational skills;   
* Understanding of communications and engagement methodologies;   
* Problem-solving skills;  
* Computer skills using Microsoft Office or other similar software;   
* Personal computer with internet connection;  
* Team player.

### Research specialist

**Attributions**
* Develop objectives and design research projects and proposals;  
* Formulate and conduct scientific research methodology (survey, observation, interviews, focus groups, experiments, secondary data analysis / archival study;  
* Replicate, evaluate, and refine research strategies and approaches and recommend improvements;  
* Test, customize, and implement new methods and procedures;  
* Propose techniques to improve research quality;  
* Contribute to and write research findings for publications, papers, presentations, grants, and other documents.

**Requirements**
* Written and verbal skills (English and Romanian);  
* Knowledge of research principles, concepts, practices, and methods;  
* Attention to detail and good organizational skills;   
* Mathematical, analytical, and research skills;   
* Problem-solving skills;  
* Computer skills using Microsoft Office or other similar software;   
* Knowledge in using Google Docs, Survey Monkey and/or other survey platforms;  
* Personal computer with internet connection;  
* Team player.

### Graphic designer

**Attributions**
* Propose design concepts;  
* Use digital illustration, photo and video editing software, and layout software to create designs;  
* Test graphics across various media;  
* Develop illustrations, logos and other designs using software or by hand;  
* Work with copywriters and creative director to produce final design.

**Requirements**
* A strong eye for visual composition;  
* Able to give and receive constructive criticism;  
* Creative skills;  
* Knowledge of Adobe PhotoShop, Illustrator, Sketch, InDesign, and other graphic design software;   
* Attention to details;  
* Personal computer with internet connection;  
* Team player.

### PR Specialist

**Attributions**
* Enhance the company’s voice and presence through online and offline channels;  
* Draft press releases, pitches, case studies, white papers, and media summaries;  
* Build relationships with new media contacts and maintain relationships with existing contacts;  
* Write press releases, speeches and other PR copy;  
* Ensure all communication is cohesive with the brand image;  
* Track and analyze media coverage to inform future campaigns;  
* Measure PR program impacts using regular reporting;  
* Organize, schedule, and prepare key leaders for press interviews;  

**Requirements**
* Written and verbal skills (English and Romanian);  
* Ability to pitch to media;  
* Creative skills;  
* Aptitude in presentation and public speaking
* Ability to manage crisis situations;   
* Attention to details;  
* Computer skills using Microsoft Office or other similar software;  
* Personal computer with internet connection;  
* Team player.

**Comment by Traveler3568** [comment]
I suggest changing the styling of the panels:
* Place arrow on the left
* Arrow color #16a99f
* Title background color - white
![Panels preview](https://user-images.githubusercontent.com/69460413/91711999-94f29d00-eb8f-11ea-980c-d30784d4c329.png)

**Comment by archblob** [comment]
I'll address this as part of #20
