### ISSUE TITLE
Letter case issue

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#34]
Page title "implica-te" is currently set to capitalize each word and needs to be changed to sentence case.
![image](https://user-images.githubusercontent.com/69460413/104445643-00b72e80-55a2-11eb-9bb0-9e790e174cdf.png)

**Comment by archblob** [comment]
We currently have **Apel Pentru Voluntari** for the `HAI IN ECHIPA ` page title.
That will now become **Apel pentru voluntari**. Is that intended?
No other pages will be affected.
