### ISSUE TITLE
Implement online donations

### ISSUE THREAD

**Issue by archblob** [communitypoweredbydlot/community-website#41]
We currently have no contract with any payments provider and the only way to accept donations is through a bank transfer.
Right now this issue is just a shell and details will be added once we are ready to implement it.

**Comment by Traveler3568** [comment]
**Thank you page**
**EN**
Thank you for your contribution.
We use donations only for the purpose of carrying out our organizationțs activity. 
Follow us on social media to stay up to date with our projects.
[social media icons]
Find out other ways you can support us: https://www.asociatiacommunity.ro/en/supportus

**RO**
Îți mulțumim pentru donație. 
Folosim sumele primite doar în scopul desfășurării activității asociației. 
Urmărește-ne pe social media pentru a fi la curent cu proiectele noastre. 
[social media icons]
Află mai multe depsre modurile în care ne poți susține: https://www.asociatiacommunity.ro/supportus

**Comment by Traveler3568** [comment]
**Internal regulation**
All information currently displayed under "Terms and Conditions"

**Data protection**
[POLITICA DE CONFIDENTIALITATE - EN.pdf](https://github.com/communitypoweredbydlot/community-website/files/6071040/POLITICA.DE.CONFIDENTIALITATE.-.EN.pdf)
[POLITICA DE CONFIDENTIALITATE - RO.pdf](https://github.com/communitypoweredbydlot/community-website/files/6071041/POLITICA.DE.CONFIDENTIALITATE.-.RO.pdf)

**Terms and conditions**
[Termeni si conditii - EN.pdf](https://github.com/communitypoweredbydlot/community-website/files/6071042/Termeni.si.conditii.-.EN.pdf)
[Termeni si conditii - RO.pdf](https://github.com/communitypoweredbydlot/community-website/files/6071043/Termeni.si.conditii.-.RO.pdf)

**Comment by archblob** [comment]
PayLike approved our account and we have a live solution.
