### ISSUE TITLE
Update links/forms and add missing information

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#54]
**Issue**
1. Missing info on both Romanian and English pages regarding the 230 form, as shown in the attached image (form 230). 
![form 230](https://user-images.githubusercontent.com/69460413/109929825-9718ee00-7ccf-11eb-9b26-bfd2e16fd41a.jpg)
2. Downloadable 230 is incomplete

3. When reffering to the Trip and Pick campaign we should use the hashtag (image povestea_1)
![povestea_1](https://user-images.githubusercontent.com/69460413/109929043-c844ee80-7cce-11eb-804b-355c22072820.jpg)
4. Call for volunteers displays email address instead of #TripAndPick (image Call for Volunteers)
![Call for volunteers](https://user-images.githubusercontent.com/69460413/109929038-c7ac5800-7cce-11eb-8d5b-8355056c671d.jpg)
5. Contact info placed in footer is not "clickable"

6. Difficulty in finding social media information as it is placed only in "Support us" page and mobile menu. 

**Describe the solution you'd like**
1. Add video and create hiperlink to the completion instructions and example of 230 form
[Instructiuni completare formular 230.pdf](https://github.com/communitypoweredbydlot/community-website/files/6081749/Instructiuni.completare.formular.230.pdf)
[Model formular 230 completat.pdf](https://github.com/communitypoweredbydlot/community-website/files/6081751/Model.formular.230.completat.pdf)
https://user-images.githubusercontent.com/69460413/109929959-bf085180-7ccf-11eb-9765-827d2085c965.mp4

2. Upload pre-filled downloadable 230 Form
[Formular 230_Asociatia Community.pdf](https://github.com/communitypoweredbydlot/community-website/files/6081846/Formular.230_Asociatia.Community.pdf)

3/4. Hyperlink #TripAndPick with social media (https://www.instagram.com/explore/tags/tripandpick/ or https://www.facebook.com/hashtag/tripandpick) - pages Call for volunteers/Povestea, both English and Romanian

5. Create hyperlinks for contact details (tel, mailto)

6. Add social media icons in footer

**Comment by archblob** [comment]
I'm not seeing **5**, the email address has a `mailto` and the phone number has a `tel`. In Chrome on Windows when I click on either the appropriate action is started.

**Comment by strugure** [comment]
@Traveler3568 Regarding pre-filled downloadable form from point 2, which link should I update to download this form ?
<img width="903" alt="link_location" src="https://user-images.githubusercontent.com/14944052/110248331-272d9080-7f79-11eb-9061-17ac285b4d9e.png">
Or if other pleas let me know where. 👯

**Comment by Traveler3568** [comment]
In the first sentence. "Download the form **here**"

**Comment by strugure** [comment]
@archblob 
1) I added locally (static/forms) all the documents and also the video (54mb). If you have a better suggestion let me know.
2) Initially I wanted to add them in assets, but I did not manage to make them visible, I tried both with require and using @assets/~assets. If it's preferred to have them in assets please give me some implementation hints 😸 

@Traveler3568 
I've added the social links in the footer under the phone number. Let me know if it should be placed elsewhere.
<img width="600" alt="Screenshot 2021-03-08 at 21 32 07" src="https://user-images.githubusercontent.com/14944052/110371623-e8b9d380-8055-11eb-8534-42cb64181904.png">

**Comment by Traveler3568** [comment]
Great! Tnx

**Comment by archblob** [comment]
@strugure static is the right place for this kind of resource.
Regarding the video, can we drop some useless frames and compress it? 54mb is to much for what it provides.
Maybe we can even make it as a gif or if not re-record it as one. We should be able to squeeze it in a few megabytes.

**Comment by Traveler3568** [comment]
Guys, please can you fix this?
![support us](https://user-images.githubusercontent.com/69460413/110793799-b4286080-827d-11eb-9b3f-4b675092e90e.jpg)
Emal tripandpick@asociatiacommunity.ro
Social media chat: direct link to messenger m.me/asociatiacommunity or link to Facebook page https://www.facebook.com/asociatiacommunity, whichever you think it's better

**Comment by archblob** [comment]
> Guys, please can you fix this?
> ![support us](https://user-images.githubusercontent.com/69460413/110793799-b4286080-827d-11eb-9b3f-4b675092e90e.jpg)
> Emal [tripandpick@asociatiacommunity.ro](mailto:tripandpick@asociatiacommunity.ro)
> Social media chat: direct link to messenger m.me/asociatiacommunity or link to Facebook page https://www.facebook.com/asociatiacommunity, whichever you think it's better

The regression happened when introducing card payments on 07.03.2021 in ed96bcc6232b7df602728a64289eceed893ff7c3.
I've pushed 1.3.2 and it's now as it was before.
