### ISSUE TITLE
Online donations not available for certain devices

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#79]
Privacy consent checkbox is not visible on certain devices, therefore the "Donate" button is not clickable. 

@strugure the bug does not occur only for Safari browser users but also Chrome (on Iphone). 
I can't provide screenshots but since you have an Iphone I assume you can make some tests.

**Comment by archblob** [comment]
You can test with a service like https://www.browserstack.com/.
This is what it looks like with in Safari on an IPhone 11

<img width="448" alt="iphone_safari_checkbox" src="https://user-images.githubusercontent.com/1261457/128512652-831cd989-f0d3-434c-9fd2-b36f8d1b6a08.png">

The checkbox is present and clickable but very, very small.
I'll into what we can do.

**Comment by archblob** [comment]
@Traveler3568 @strugure The checkbox should now look ok and function as expected.
