### ISSUE TITLE
Corectare greșeli text website

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#85]
La linkul de mai jos găsiți un document în care sunt evidențiate cu galben corecturile pe care trebuie să le facem la textele de pe site. 
https://docs.google.com/document/d/1qS-7Q9KgRMlurlLaMAe_F7R9IDwqbgQAUWL5tUGkoGs/edit?usp=sharing

**Comment by archblob** [comment]
In prod with #86
