### ISSUE TITLE
Modificări pagina Redirecționare impozit

### ISSUE THREAD

**Issue by Traveler3568** [communitypoweredbydlot/community-website#89]
Este necesară înlocuirea documentelor de anul trecut cu cele pentru anul acesta. 
Aici găsiți Formularul 230 ce trebuie completat de contribuabili și Modelul de completare a formularului
[Formular 230_2021_Asociatia Community.pdf](https://github.com/communitypoweredbydlot/community-website/files/8131099/Formular.230_2021_Asociatia.Community.pdf)
[Model completare formular 230_2021.pdf](https://github.com/communitypoweredbydlot/community-website/files/8131102/Model.completare.formular.230_2021.pdf)

**Comment by Traveler3568** [comment]
@strugure te rog modifici la FAQ, pagina de [redirecționare](https://www.asociatiacommunity.ro/incometax), penultima întrebareȘ Este corect trecut anul 2020? să pui 2021 
![image](https://user-images.githubusercontent.com/69460413/156563496-ac94cce5-3679-41f6-90fa-e200209c5ec7.png)

**Comment by strugure** [comment]
@Traveler3568 Am schimbat si pe romana si pe engleza.
